include:
  - project: 'xchange-gambool/pipeline-templates'
    ref: master
    file: 'xchange-gambool-gradle-kotlin.yml'

before_script:
  - export APP_TYPE=services
  - export APP_NAME=activity-gradle
  - export APP_HEROKU_NAME_UAT=gambool-activity-service-uat
  - export APP_HEROKU_NAME=gambool-activity-service
  - export TARGET_DIR=activity-app/build/libs
  - export UAT_URL="https://gambool-activity-service-uat.herokuapp.com/services"
  - export PROD_URL="https://gambool-activity-service.herokuapp.com/services"

